type Course {
    id: ID!
    name: String!
    rate: Int
    finish_time: String
    owner_id: String
    created: String
    deleted: Boolean
}

input CourseInput {
    id: ID!
    name: String!
    rate: Int
    finish_time: String
    owner_id: String
    created: String
    deleted: Boolean
}

type Mutation {
    createCourse(id: ID!, name: String!, rate: Int, finish_time: String, owner_id: String): Course!
    updateCourse(id: ID!, name: String!, rate: Int, finish_time: String, owner_id: String): Course
    deleteCourseById(id: ID!): Boolean
}